application: algo-vis
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /generated
  static_dir: generated

- url: /lib
  static_dir: lib

- url: .*
  script: main.py

builtins:
- remote_api: on
